# application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:8080/board_crud?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root  # -> \uC55E\uC11C \uC785\uB825\uD588\uB358 MySQL username \uC785\uB825
    password: 1234  # -> \uC55E\uC11C \uC124\uC815\uD588\uB358 MySQL \uBE44\uBC00\uBC88\uD638 \uC785\uB825
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
    hibernate:
      ddl-auto: create-drop

#logging.level:
#  org.hibernate.SQL: debug