# application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board_crud?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root  # -> ?? ???? MySQL username ??
    password: 1234  # -> ?? ???? MySQL ???? ??
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
    hibernate:
      ddl-auto: create-drop

logging.level:
  org.hibernate.SQL: debug

servlet:
  encoding:
    charset: UTF-8
    enabled: true
    force: true